alias gst='git status'
alias gsl='git status | less'
alias gap='git add -p'
alias gco='git co'
alias gpff='git pull --ff-only'
alias gprb='git pull --rebase'
alias git-log='git log --name-status'
alias git-diff-staged='git diff --staged'
