#!/usr/bin/env bash
set -eo

theme=

if grep -q light ~/.config/.theme; then
  # make dark
  theme=dark
  sed -i 's/set background=light/set background=dark/' ~/.config/nvim/init.vim
  sed -i "s/gruvbox_light/gruvbox_dark/" ~/.config/kitty/kitty.conf
  sed -i "s/gruvbox-light/gruvbox-dark/" ~/.gitconfig
  sed -i "s/gruvbox-light/gruvbox-dark/" ~/.config/awesome/rc.lua
else
  # make light
  theme=light
  sed -i 's/set background=dark/set background=light/' ~/.config/nvim/init.vim
  sed -i "s/gruvbox_dark/gruvbox_light/" ~/.config/kitty/kitty.conf
  sed -i "s/gruvbox-dark/gruvbox-light/" ~/.gitconfig
  sed -i "s/gruvbox-dark/gruvbox-light/" ~/.config/awesome/rc.lua
fi

echo $theme > ~/.config/.theme
pkill -USR1 kitty
echo 'awesome.restart()' | awesome-client &

# reload vim instances
#original_window=$(xdotool getwindowfocus)
#for pid in $(xdotool search --name ': nvim'); do
  #sleep 0.5
  #xdotool windowfocus $pid
  #sleep 0.1
  #xdotool key Escape
  #sleep 0.1
  #xdotool type ':so $MYVIMRC'
  #sleep 0.1
  #xdotool key Return
#done
#xdotool windowfocus $original_window

echo "Toggled to $theme theme"
