#!/usr/bin/env bash
set -eo

theme=

if grep -q light ~/.config/.theme; then
	# make dark
	theme=dark
	sed -i 's/background = "light"/background = "dark"/' ~/.config/astronvim/lua/user/options.lua
	sed -i "s/gruvbox_light/gruvbox_dark/" ~/.config/kitty/kitty.conf
	sed -i "s/gruvbox-light/gruvbox-dark/" ~/.gitconfig
	sed -i "s/gruvbox-light/gruvbox-dark/" ~/.config/awesome/themes/gruvbox/theme.lua
	sed -i "s/gruvbox-light/gruvbox-dark/" ~/.config/rofi/config.rasi
	sed -i "s/myTheme = gruvboxLight/myTheme = gruvboxDark/" ~/.config/taffybar/taffybar.hs
	sed -i "s/myTheme = gruvboxLight/myTheme = gruvboxDark/" ~/.config/xmonad/xmonad.hs
	ln -fs ~/.config/bg/retro-linux-dark.png ~/.config/bg/retro-linux.png
	ln -fs ~/.config/taffybar/gruvbox-dark.css ~/.config/taffybar/taffybar.css
	sed -i '/gruvbox_light/s/^/#/' ~/.config/dunst/dunstrc
	sed -i '/gruvbox_dark/s/^#//' ~/.config/dunst/dunstrc
else
	# make light
	theme=light
	sed -i 's/background = "dark"/background = "light"/' ~/.config/astronvim/lua/user/options.lua
	sed -i "s/gruvbox_dark/gruvbox_light/" ~/.config/kitty/kitty.conf
	sed -i "s/gruvbox-dark/gruvbox-light/" ~/.gitconfig
	sed -i "s/gruvbox-dark/gruvbox-light/" ~/.config/awesome/themes/gruvbox/theme.lua
	sed -i "s/gruvbox-dark/gruvbox-light/" ~/.config/rofi/config.rasi
	sed -i "s/myTheme = gruvboxDark/myTheme = gruvboxLight/" ~/.config/taffybar/taffybar.hs
	sed -i "s/myTheme = gruvboxDark/myTheme = gruvboxLight/" ~/.config/xmonad/xmonad.hs
	ln -fs ~/.config/bg/retro-linux-light.png ~/.config/bg/retro-linux.png
	ln -fs ~/.config/taffybar/gruvbox-light.css ~/.config/taffybar/taffybar.css
	sed -i '/gruvbox_dark/s/^/#/' ~/.config/dunst/dunstrc
	sed -i '/gruvbox_light/s/^#//' ~/.config/dunst/dunstrc
fi

# restart stuff
feh --bg-scale --no-fehbg ~/.config/bg/retro-linux.png
pkill -xf /usr/bin/dunst
pkill -USR1 kitty

# record current theme
echo $theme >~/.config/.theme
notify-send "Toggled to $theme theme"
